Add API functionality
KDlamini/Leaderboard pull request #2
Opened 2021-10-07 13:45 UTC by KDlamini

This feature will be covering the following functionality:
- Create a new game with the Leaderboard API using the POST method.
- Implement the "Refresh" button for receiving data from the API.
- Implement the form "Submit" button for sending data to the API.
- Uses async and await JavaScript features to consume the API

2021-10-07 14:24 UTC, dasileker requested changes
### **Hi @KDlamini,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-07 14:24 UTC, dasileker commented on README.md
> +[https://kdlamini.github.io/Leaderboard/](https://kdlamini.github.io/Leaderboard/)
- [ ] The `Live demo` is not working, please update your link.

2021-10-07 14:24 UTC, dasileker commented on README.md
> +```
- [ ] The `Getting Started` should have more details on how the user can download the repo and navigate to it.

2021-10-07 14:24 UTC, dasileker commented on src/api.js
> +    return json;
- [ ] I left this review here because I can't select the right line.

- [ ] The `createGame && the getScore` do not work, the **API** is not showing any entered data provided. I do see a lot of names and scores but when I try to add mine the API doesn't add anything???

2021-10-08 12:30 UTC, george-shammar approved these changes
Hi @KDlamini , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

:heavy_check_mark: I was able to add score and the score reflected. :clap: 

Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-08 12:32 UTC, merged